org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=false
org.gradle.caching=true
org.gradle.jvmargs=-Xmx3G -XX:+UseG1GC -Dfile.encoding=UTF-8 -Dnet.minecraftforge.gradle.check.certs=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.2
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

kineticcore_version=26.8.17
kineticcore_version_range=[26.8.17,)
curios_version=5.14.1
curios_version_range=[5.10.0,)
kubejs_version=2001.6.5-build.16
kubejs_version_range=[2001.6.5,)
rhino_version=2001.2.12
architectury_version=9.2.14

mod_id=kineticarmory
mod_name=Kinetic Armory
mod_license=GPLv3
mod_version=26.8.10
use_auto_version=true
mod_group_id=dev.xyat.kineticarmory
mod_authors=XYAT
mod_description=Armor set systems extracted from kineticcore as an independent companion mod.

local_libs_dir=D:/IDEA_Caches/libs
output_mods_dir=D:/NEWMODS
